### ISSUE TITLE
Suggestion: Ability to set default wall height (or work with clone walls tool)

### ISSUE THREAD

**Issue by Dumbhuman** [schultzcole/FVTT-Wall-Height#1]
**THANK YOU!**

I know this is a pre-release and you probably have plenty of plans for improvement, but the number one suggestion I'd make is the ability to set default heights so that you can lay down walls with a specific height rather than needing to set it afterwards.

**Comment by schultzcole** [comment]
Good idea. I will see if I can get it to work with the clone walls tool. Until then, batch modifying all of the walls after placing them should be a decent workaround.

**Comment by schultzcole** [comment]
@Dumbhuman once again, thank you for your interest in this module. As I mentioned in other issues, I don't intend to release any more updates for Wall Height, so I will be closing this issue.
