### ISSUE TITLE
Bug: Movement through walls if above/below

### ISSUE THREAD

**Issue by Valdacil** [schultzcole/FVTT-Wall-Height#11]
Issue #4 - Allow movement through walls when token is above/below the wall

This feature appears to be broken.  I created a wall, set it to top = 0, bottom = Infinity (also tried 200 just in case).  Set token to height = +5.  It should totally go over the wall, but instead is blocked when using the arrow keys to move it.  I also created a wall set to top = Infinite, bottom = 0, token = -20.  It could not move under the wall using the arrow keys to move.  In both scenarios the vision worked properly however.

Foundry 0.7.7
Module 3.0.0

**Comment by schultzcole** [comment]
This isn't a bug so much as a feature that was never implemented. I don't intend on adding new features at this time.
