### ISSUE TITLE
Wall Height and Haste Mod - DM works fine, Players get broken movement

### ISSUE THREAD

**Issue by apoapostolov** [schultzcole/FVTT-Wall-Height#3]
Activate Wall Height and Haste 0.4.9 (available at https://gitlab.com/jesusafier/haste/)

DM side works great. On Player side, major game-breaking issue when attempting to move icon via drag and drop. Upon dropping, the token doesn't move and a select area is triggered causing the mouse to select area until right click cancels the selection. 

I contacted Haste dev as well: https://gitlab.com/jesusafier/haste/-/issues/6

**Comment by schultzcole** [comment]
Hello @apoapostolov, I'm sorry it took so long to get around to this. I think that compatibility between wall height and haste should be working in the Wall Height 2.0.0 release candidate. I would appreciate if you could test it and give feedback! The release candidate is not yet available on the Foundry package listing, but you can install it via manifest with this link: https://raw.githubusercontent.com/schultzcole/FVTT-Wall-Height/2.0.0rc/module.json
Thank you.
