### ISSUE TITLE
Feature Request: Allow Visibility of Token(s) Beyond a Wall if Token's Height is Above/Below that Wall's Settings

### ISSUE THREAD

**Issue by Dumbhuman** [schultzcole/FVTT-Wall-Height#5]
Essentially allowing a flying token not only to see over the wall, but also to be seen over the wall by those on the other side.

I'm not sure how feasible that is, but it would certainly be a nice feature to have when facing flying enemies in areas with lots of walls (like a dragon flying over a village).

**Comment by schultzcole** [comment]
This is a good suggestion, but I'm not sure if there is a great way to implement it satisfactorily without doing some proper geometry calculations to determine visibility, and honestly I'd prefer to avoid that.

For example, with a naive implementation, a guard standing on top of a castle wall would be visible by tokens on the ground outside of the wall, even if the guard was standing away from the edge of the wall.

I'll do some thinking and see if I can come up with a good way to do this.

**Comment by Dumbhuman** [comment]
I agree that you wouldn't want to dive down the rabbit hole of requiring all kinds of hypotenuses to be calculated and such, but maybe a more simplistic threshold of "if Token X exceeds Wall Y's Height by at least 10, then make Token X visible to tokens on other side of Wall Y."  That would allow for Tokens placed on top of buildings/walls to still be occluded by them while making flyers more visible.  Just an idea.

**Comment by imposeren** [comment]
For tokens of same height it is relatively simple to check visibility on different elevation: 
Token "A" can see other token "B" of same height on higher ground only if token B is closer to the wall.

Most likely not visible (A is closer to the wall than B  or distances equal):
```
         . . .B 
         X######
         X######
         X######
         X######
         X######
  A. . . X######
----------------
```

Barely visible (B is a little closer to the wall than A):
```
         . . B 
         X######
         X######
         X######
         X######
         X######
  A. . . X######
----------------
```


"half-visible" (B is 2 times closer to he wall than A):
```
         . B 
         X######
         X######
         X######
         X######
         X######
  A. . . X######
----------------
```

If height of token B is different, then "visibility threshold" can be approximated as proportionally bigger or proportionally smaller value:
* If token B is 25% higher than A, then it stops being visible when `BX > 1.25×AX`
* If token B is 25% lower than A, then it stops being visible when `BX > 0.75×AX`

**Comment by imposeren** [comment]
![triangles](https://user-images.githubusercontent.com/1067274/90976112-0c4a8000-e543-11ea-9824-9ea74f801f25.png)


It's easy to spot similar triangles here. And similar triangles have proportional side lengths:
https://www.varsitytutors.com/hotmath/hotmath_help/topics/similar-triangles#:~:text=Two%20triangles%20are%20said%20to,sides%20are%20of%20equal%20length.

So I think that some criterion for "being in shadow" can be formulated purely on distances+heights+proportions between them.

I'm tired now, but I can try to provide actual formula a bit later. 

P.S. If we are considering eyes to always be "on top of character" then top "maybe shadow" can be ignored and bottom "maybe shadow" will become part of simple shadow

**Comment by schultzcole** [comment]
Sorry, I should have closed this issue earlier. I do not intend to implement this feature in Wall Height, though I encourage others to fork the module and add it if they are passionate about the idea.

At this time, the only updates I plan on releasing for Wall Height are bugfixes if they are game breaking, and even then I probably will not maintain it after 0.7.x drops to beta/stable.
