### ISSUE TITLE
Feature Request: Compatibility with dynamiceffects

### ISSUE THREAD

**Issue by tposney** [schultzcole/FVTT-Wall-Height#8]
Firstly, Love the mod.
Dynamic effects has a flag
```
game.settings.get("dynamiceffects", "playerControlsInvisibleTokens")
```
which enables players to manipulate their owned tokens even if they are invisible.
It patches isVisible and updateToken.
If possible it would be great for wall heights to add in the following change if the above flag is enabled:
The line
```
if (token.data.hidden && !game.user.isGM) return;
```
becomes
```
 if (token.data.hidden && !(game.user.isGM || token.actor?.hasPerm(game.user, "OWNER"))) return;
```
If you wanted to add in the "players control invisible tokens" as part of this mod that would be good too and I can send you the isVisible patch as well.

**Comment by schultzcole** [comment]
Thanks for the request. I'd be happy to add compatibility for this.

I've made the following change to my `updateToken` patch:
```js
        // Add compatibility for dynamic effects player controls invisible tokens setting
        const deCtrlInvisTokens = game.settings.get("dynamiceffects", "playerControlsInvisibleTokens");
        const playerCanView = deCtrlInvisTokens && token.actor?.hasPerm(game.user, "OWNER");
        if (token.data.hidden && !(game.user.isGM || playerCanView)) return;
```

Does that look correct?

I don't think I want to completely absorb this functionality into wall height though. I'd rather not have the scope get much larger than it already is.

**Comment by schultzcole** [comment]
Added in 1.0.4
